name: Package
description: Stub action for multi-platform packaging

runs:
  using: "composite"
  steps:

  - name: Package (OSX)
    if: runner.os == 'MacOS'
    uses: "./.github/workflows/package/osx"

  - name: Package (Windows)
    if: runner.os == 'Windows'
    uses: "./.github/workflows/package/windows"
