name: Get Code Version

runs:
  using: "composite"
  steps:

  - name: Grep Version
    shell: bash
    run: |
      set -ex
      VERSION=`grep "#define JV2VERSION" version.h | sed "s/.*\"\(.*\)\"/\1/g"`
      echo "JV2 code version is ${VERSION}"
      echo "jv2Version=${VERSION}" >> ${GITHUB_ENV}
