variables:
  BUILD_CFG: 'Release'
  CONAN_USER_HOME: '$(Build.SourcesDirectory)/conan'

steps:
  - task: Cache@2
    displayName: "Cache conan packages"
    inputs:
      key: 'conan | "$(Agent.OS)" | $(Build.SourcesDirectory)/frontend/cmake/Modules/conan-jv2.cmake'
      path: "$(CONAN_HOME)"
  - bash: |
      set -ex
      sudo scripts/linux/setup-for-development-ubuntu.sh
    displayName: 'Install Prerequisites'
  - bash: |
      set -ex
      cd frontend
      mkdir build && cd build
      cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DJV2_USE_CONAN=ON ../
      cmake --build .
    displayName: 'Build Frontend'
  - bash: |
      set -ex
      cd backend
      python3 -m pip wheel --wheel-dir=wheels .
