parameters:
  - name: qtver
    default: 6.1.2

steps:
  - bash: |
      set -ex
      wget https://raw.githubusercontent.com/disorderedmaterials/scripts/master/prep-appimage
      chmod u+x ./prep-appimage
      echo -e "\nRetrieving linuxdeploy...\n"
      wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage -O linuxdeployqt.AppImage
      chmod u+x ./linuxdeployqt*.AppImage
    displayName: 'Install Prerequisites'
  - bash: |
      set -ex
      export VERSION=`grep "#define JV2VERSION" version.h | sed "s/.*\"\(.*\)\"/\1/g"`
      ./prep-appimage -a jv2 -v ${VERSION} -b build/jv2
    displayName: 'Prepare AppDir'
  - bash: |
      set -ex
      # Set environment vars to locate Qt
      QT_BASE_DIR="/opt/qt${{ parameters.qtver }}/gcc_64"
      export QTDIR=$QT_BASE_DIR
      export PATH=$QT_BASE_DIR/bin:$PATH
      export QMAKE=$QT_BASE_DIR/bin/qmake
      # Extract the version from the source
      export VERSION=`grep "#define JV2VERSION" version.h | sed "s/.*\"\(.*\)\"/\1/g"`
      # Get extra dependencies needed by the App Image
      sudo apt install libxkbcommon-x11-0 libxcb-render0 libxcb-render-util0 libxcb-shape0 libxcb-randr0 libxcb-xfixes0 libxcb-xkb1 libxcb-sync1 libxcb-shm0 libxcb-icccm4 libxcb-keysyms1 libxcb-image0 libxcb-util1 libfontconfig
      # Run on the targets
      ./linuxdeployqt.AppImage jv2-${VERSION}.AppDir/usr/bin/jv2 -unsupported-allow-new-glibc -verbose=3
    displayName: 'Create AppImages'
  - bash: |
      set -ex
      mkdir packages
      mv JournalViewer2-*-x86_64.AppImage packages
    displayName: 'Move Artifacts'