steps:
  - bash: |
      set -ex
      sudo scripts/linux/setup-for-development-ubuntu.sh
    displayName: 'Install Prerequisites'
  - bash: |
      set -ex
      cd frontend
      mkdir build && cd build
      cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DJV2_USE_CONAN=ON ../
      cmake --build .
    displayName: 'Build Frontend'
  - bash: |
      set -ex
      cd backend
      python3 -m pip wheel --wheel-dir=wheels .
