trigger:
  branches:
    include:
    - develop
    - refs/tags/*
  paths:
    exclude:
    - .azure-pipelines/release.yml
    - .azure-pipelines/pr.yml
    - README.md

stages:
  - template: templates/codeQualityChecks.yml

  - stage: 'build'
    displayName: 'Build'
    jobs:
      - job: 'windows'
        displayName: 'Windows'
        pool:
          vmImage: 'windows-latest' 
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/windowsBuild.yml
      
      - job: 'linux'
        displayName: 'Linux'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/linuxBuild.yml
      
      - job: 'osx'
        displayName: 'OSX'
        pool:
          vmImage: 'macos-latest'
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/osxBuild.yml