name: Publishing

on:
  workflow_call:
    inputs:
      publishType:
        required: true
        type: string
    secrets:
      HARBOR_USER:
        description: "Username for Harbor access"
      HARBOR_SECRET:
        description: "Key for Harbor access"

jobs:

  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Environment Variables
        uses: "./.github/workflows/setup"
      - name: Publish
        uses: "./.github/workflows/publish"
        with:
          publishType: ${{ inputs.publishType }}
        env:
          HARBOR_USER: ${{ secrets.HARBOR_USER }}
          HARBOR_SECRET: ${{ secrets.HARBOR_SECRET }}
      - name: Update Version Information
        if: ${{ inputs.publishType == 'release' }}
        uses: "./.github/workflows/update-release-info"
        with:
          releaseVersion: ${{ env.jv2Version }}

