name: Generate Caches

on:
  workflow_dispatch:
    inputs:
      cacheLinux:
        type: boolean
        default: true
      cacheWindows:
        type: boolean
        default: true

jobs:

  Cache:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: "./.github/workflows/setup"
      - name: "Build (Cache Only)"
        uses: "./.github/workflows/build"
        with:
          cacheOnly: true
          linuxEnabled: ${{ inputs.cacheLinux }}
          windowsEnabled: ${{ inputs.cacheWindows }}
          linuxCacheOnly: ${{ inputs.cacheLinux }}
          windowsCacheOnly: ${{ inputs.cacheWindows }}

