name: Generate Caches

on:
  workflow_dispatch:

jobs:

  Cache:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Environment
        uses: "./.github/workflows/set-environment"
      - name: "Build (Cache Only)"
        uses: "./.github/workflows/build"
        with:
          cacheOnly: true

