name: Continuous

on:
  push:
    branches:
    - 'develop'
    paths-ignore:
    - '.github/workflows/cache.yml'
    - '.github/workflows/pr.yml'
    - '.github/workflows/release.yml'
    - 'README.md'

jobs:

  QC:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set Environment Variables
      uses: "./.github/workflows/setup"
    - name: Quality Control
      uses: "./.github/workflows/qc"

  Test:
    needs: QC
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set Environment Variables
      uses: "./.github/workflows/setup"
    - name: "Test (Backend)"
      uses: "./.github/workflows/test"

  Build:
    needs: Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set Environment Variables
      uses: "./.github/workflows/setup"
    - name: "Build (${{ matrix.os }})"
      uses: "./.github/workflows/build"

  Package:
    needs: Build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set Environment Variables
      uses: "./.github/workflows/setup"
    - name: "Package (${{ matrix.os }})"
      uses: "./.github/workflows/package"

  Publish:
    needs: Package
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set Environment Variables
      uses: "./.github/workflows/setup"
    - name: Publish
      uses: "./.github/workflows/publish"
      with:
        isRelease: false
      env:
        HARBOR_USER: ${{ secrets.HARBOR_USER }}
        HARBOR_SECRET: ${{ secrets.HARBOR_SECRET }}
