name: Continuous

on:
  push:
    branches:
    - 'develop'
    paths-ignore:
    - '.github/workflows/cache.yml'
    - '.github/workflows/pr.yml'
    - '.github/workflows/release.yml'
    - 'README.md'

jobs:

  BuildAndPackage:
    uses: "./.github/workflows/_build_and_package.yml"

  Publish:
    needs: [BuildAndPackage]
    uses: "./.github/workflows/_publishing.yml"
    with:
      isRelease: false
