name: Pull Request

on:
  pull_request:
    branches:
    - '*'
    paths-ignore:
    - '.github/workflows/cache.yml'
    - '.github/workflows/continuous.yml'
    - '.github/workflows/release.yml'
    - 'README.md'

jobs:

  BuildAndPackage:
    uses: "./.github/workflows/_build_and_package.yml"
