name: Pull Request

on:
  pull_request:
    branches:
    - '*'
    paths-ignore:
    - '.github/workflows/cache.yml'
    - '.github/workflows/continuous.yml'
    - '.github/workflows/release.yml'
    - 'README.md'

jobs:

  QC:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set Environment Variables
      uses: "./.github/workflows/set-environment" 
    - name: Quality Control
      uses: "./.github/workflows/qc"

  Test:
    needs: QC
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set Environment Variables
      uses: "./.github/workflows/set-environment" 
    - name: "Test (Backend)"
      uses: "./.github/workflows/test"

  Build:
    needs: Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set Environment Variables
      uses: "./.github/workflows/set-environment" 
    - name: "Build (${{ matrix.os }})"
      uses: "./.github/workflows/build"

  Package:
    needs: Build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Get Code Version
      uses: "./.github/workflows/get-version"
    - name: "Package (${{ matrix.os }})"
      uses: "./.github/workflows/package"
