name: Release

on:
  push:
    branches:
    - 'release/*'
    paths-ignore:
    - '.github/workflows/cache.yml'
    - '.github/workflows/continuous.yml'
    - '.github/workflows/pr.yml'
    - 'README.md'

jobs:


  BuildAndPackage:
    uses: "./.github/workflows/_build_and_package.yml"

  Publish:
    needs: [BuildAndPackage]
    uses: "./.github/workflows/_publishing.yml"
    with:
      isRelease: false
