name: Build & Deploy Singularity Image

on:
  push:
    branches: ["backend-isisdatacache"]

jobs:
  singularity-build:
    runs-on: ubuntu-20.04

    steps:
      - name: Install singularity
        uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Singularity Image
        run: |
          cd scripts/linux
          sudo ${SINGULARITY_ROOT}/bin/singularity build jv2-build.sif ./jv2-build.def
          sudo ${SINGULARITY_ROOT}/bin/singularity build jv2.sif ./jv2.def

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: jv2.sif
          path: scripts/linux/jv2.sif
          if-no-files-found: error
